repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: dotnet format apps/venicio/DevBoardVS/DevBoardVS.csproj
        language: system
        pass_filenames: false

      - id: eslint-frontend-venicio
        name: eslint frontend venicio
        entry: wsl -d Ubuntu -- bash -c "cd apps/venicio/frontend && npm install && npm run lint"
        language: system
        pass_filenames: false

      - id: eslint-frontend-victor
        name: eslint frontend victor
        entry: wsl -d Ubuntu -- bash -c "cd apps/victor && npm install && npm run lint"
        language: system
        pass_filenames: false

      - id: check-required-files-venicio
        name: Check required files for Venicio
        entry: wsl -d Ubuntu -- bash -c "test -f README.md && test -f apps/venicio/docker-compose.yml"
        language: system
        pass_filenames: false
