services:
  api:
    build: .
    container_name: api-devboard
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - devnet

  db:
    image: postgres:14
    container_name: db-devboard
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devnet

volumes:
  dbdata:

networks:
  devnet:
    driver: bridge
