version: '3.8'

services:
  api:
    build: .
    container_name: api-victor
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-victor
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
